csv: # path to csv containing slide paths

output_dir: "output" # output directory

visualize: true

tiling:
  params:
    spacing: 0.5 # spacing at which to tile the slide, in microns per pixel
    tile_size: 224 # size of the tiles to extract, in pixels

model:
  level: "tile" # level at which to extract the features ("tile", "region" or "slide")
  arch: "hibou-b" # Hibou model architectures, options: ("hibou-b", "hibou-L")
  name: "hibou"
  batch_size: 1

speed:
  fp16: true # use mixed precision during model inference